### ISSUE TITLE
Remove OWM API key form repo

### ISSUE THREAD

**Issue by n0x-io** [LoneWolf4713/seraphic.dotfiles#1]
Hey hey hey! 

Stumbled across your dotfiles while looking at some hyperlock configs and yours look quite awesome :smile: 

But while looking through your files i noticed you have your openweathermaps API key in your dotfiles:
https://github.com/LoneWolf4713/seraphic.dotfiles/blob/main/dotfiles/hypr/breeze.sh

While I'm aware that those are free I still wanted to make you aware that perhaps you might want to invalidate it and make a new one so nobody can abuse this one.

**Comment by n0x-io** [comment]
Oh same key is used in https://github.com/LoneWolf4713/seraphic.dotfiles/blob/main/dotfiles/hypr/weather.sh as well.

**Comment by LoneWolf4713** [comment]
thank you, I invalidated it, you have my gratitude.
